### ISSUE TITLE
Publish Action Monitoring

### ISSUE THREAD

**Issue by Surgbc** [CitizenKonnect/gluegunplus#24]
Triggers changed from

```
 on:
   push:
     tags:
       - 'v*'
```

to 

```
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    # Execute the action on closed (merged) PR.
    types:
      [closed]
 ```
 
 Initially, tags needed to be created, requiring clones of both main repo and development fork. New work flow requires only a single cloned repo.
